# Generated by Django 5.2.5 on 2025-08-29 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('counter', models.IntegerField(default=0)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.content')),
                ('text', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Audio Content',
                'verbose_name_plural': 'Audio Contents',
            },
            bases=('app.content',),
        ),
        migrations.CreateModel(
            name='TextContent',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.content')),
                ('text', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Text Content',
                'verbose_name_plural': 'Text Contents',
            },
            bases=('app.content',),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.content')),
                ('video_url', models.URLField()),
                ('subtitles_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Video Content',
                'verbose_name_plural': 'Video Contents',
            },
            bases=('app.content',),
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_pages', to='app.content')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_contents', to='app.page')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('page', 'content')},
            },
        ),
    ]
